services:
  imagehandler:
    build: .
    environment:
      IMAGEHANDLERAUTHJSON: '{ "jsnider2.github.io": ["", "", "SSL"] }'
    healthcheck:
      test: ["CMD", "curl", "-s", "http://127.0.0.1/health-check"]
      interval: 5s
      timeout: 5s
      retries: 6
  test:
    depends_on:
      imagehandler:
        condition: service_healthy
    build:
      context: .
      dockerfile: test/Dockerfile
    volumes:
      - ./test/test-results:/test-results
